{"level":"error","message":"Login failed: Invalid credentials","timestamp":"2025-05-21T14:51:45.422Z"}
{"error":{"storageErrors":[]},"level":"error","message":"Error: Only image and video files are allowed","method":"POST","path":"/api/upload","timestamp":"2025-06-13T14:20:44.284Z"}
{"error":{"storageErrors":[]},"level":"error","message":"Error: Only image and video files are allowed","method":"POST","path":"/api/upload","timestamp":"2025-06-13T14:28:06.259Z"}
{"error":{"storageErrors":[]},"level":"error","message":"Error: Only image and video files are allowed","method":"POST","path":"/api/upload","timestamp":"2025-06-13T14:41:24.894Z"}
{"error":{"storageErrors":[]},"level":"error","message":"Error: Only image and video files are allowed","method":"POST","path":"/api/upload","timestamp":"2025-06-13T14:42:19.177Z"}
{"level":"error","message":"JWT strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:21.968Z"}
{"error":{"__augmented":true,"code":"SQLITE_ERROR","driverError":{"__augmented":true,"code":"SQLITE_ERROR","errno":1},"errno":1,"parameters":["d484a328-ff20-43d8-862b-e9e059bea845"],"query":"SELECT \"User\".\"id\" AS \"User_id\", \"User\".\"username\" AS \"User_username\", \"User\".\"password\" AS \"User_password\", \"User\".\"createdAt\" AS \"User_createdAt\" FROM \"users\" \"User\" WHERE ((\"User\".\"id\" = ?)) LIMIT 1"},"level":"error","message":"Error: SQLITE_ERROR: no such table: users","method":"GET","path":"/api/auth/me","timestamp":"2025-07-25T14:05:21.971Z"}
{"level":"error","message":"JWT strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:21.984Z"}
{"error":{"__augmented":true,"code":"SQLITE_ERROR","driverError":{"__augmented":true,"code":"SQLITE_ERROR","errno":1},"errno":1,"parameters":["d484a328-ff20-43d8-862b-e9e059bea845"],"query":"SELECT \"User\".\"id\" AS \"User_id\", \"User\".\"username\" AS \"User_username\", \"User\".\"password\" AS \"User_password\", \"User\".\"createdAt\" AS \"User_createdAt\" FROM \"users\" \"User\" WHERE ((\"User\".\"id\" = ?)) LIMIT 1"},"level":"error","message":"Error: SQLITE_ERROR: no such table: users","method":"GET","path":"/api/auth/me","timestamp":"2025-07-25T14:05:21.985Z"}
{"level":"error","message":"Local strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:27.067Z"}
{"level":"error","message":"Login error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:27.068Z"}
{"level":"error","message":"Stack trace: QueryFailedError: SQLITE_ERROR: no such table: users\n    at handler (D:\\led-soliton\\led-display-react\\server\\node_modules\\typeorm\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)\n    at replacement (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\trace.js:25:27)\n    at Statement.errBack (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\sqlite3.js:15:21)","timestamp":"2025-07-25T14:05:27.070Z"}
{"level":"error","message":"Local strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:29.372Z"}
{"level":"error","message":"Login error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:29.373Z"}
{"level":"error","message":"Stack trace: QueryFailedError: SQLITE_ERROR: no such table: users\n    at handler (D:\\led-soliton\\led-display-react\\server\\node_modules\\typeorm\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)\n    at replacement (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\trace.js:25:27)\n    at Statement.errBack (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\sqlite3.js:15:21)","timestamp":"2025-07-25T14:05:29.374Z"}
{"level":"error","message":"Local strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:34.778Z"}
{"level":"error","message":"Login error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:34.778Z"}
{"level":"error","message":"Stack trace: QueryFailedError: SQLITE_ERROR: no such table: users\n    at handler (D:\\led-soliton\\led-display-react\\server\\node_modules\\typeorm\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)\n    at replacement (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\trace.js:25:27)\n    at Statement.errBack (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\sqlite3.js:15:21)","timestamp":"2025-07-25T14:05:34.778Z"}
{"level":"error","message":"Local strategy error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:55.270Z"}
{"level":"error","message":"Login error: QueryFailedError: SQLITE_ERROR: no such table: users","timestamp":"2025-07-25T14:05:55.271Z"}
{"level":"error","message":"Stack trace: QueryFailedError: SQLITE_ERROR: no such table: users\n    at handler (D:\\led-soliton\\led-display-react\\server\\node_modules\\typeorm\\src\\driver\\sqlite\\SqliteQueryRunner.ts:133:29)\n    at replacement (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\trace.js:25:27)\n    at Statement.errBack (D:\\led-soliton\\led-display-react\\server\\node_modules\\sqlite3\\lib\\sqlite3.js:15:21)","timestamp":"2025-07-25T14:05:55.271Z"}
{"level":"error","message":"Login failed: Invalid credentials","timestamp":"2025-07-25T14:06:44.230Z"}
{"level":"error","message":"Login attempt details - Username: test","timestamp":"2025-07-25T14:06:44.231Z"}
{"level":"error","message":"Login failed: Invalid credentials","timestamp":"2025-07-25T14:11:06.532Z"}
{"level":"error","message":"Login attempt details - Username: test","timestamp":"2025-07-25T14:11:06.532Z"}
